### ISSUE TITLE
regarding how you were able to read the data on the computer

### ISSUE THREAD

**Issue by Master6996** [harout/mojo-data-capture#1]
as i am using same wiznet module for data tranfer from fpga to the computer over ethernet but i am not getting how i can read this data on the pc please help

**Comment by harout** [comment]
It's been years since I worked on this project, but I believe I had the Wiznet module send UDP packets to a static IP address. In the "wiznet5500_parameters.v" file you can see where I define the Wiznet module's IP address and the computer's IP address and port number. Assign the computer a static IP address and write a program to listen for UDP packets on a particular port.
